# Generated by Django 4.0.6 on 2023-03-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='estimatedTimeOfDeparture',
            field=models.TimeField(),
        ),
    ]
