# Generated by Django 4.0.6 on 2023-03-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0006_alter_passenger_middlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='middleName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
